# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:43
from __future__ import unicode_literals

from django.db import migrations

from .. import utils

class Migration(migrations.Migration):

    dependencies = []

    operations = []

    utils.set_operations(operations, "000_create_tables")
