# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:43
from __future__ import unicode_literals

from django.db import migrations

from .. import utils

class Migration(migrations.Migration):

    dependencies = [("common", "0001_initial")]

    operations = []

    utils.set_operations(operations, "common", "001_populate_tables", "002_add_champion_data", "003_add_item_data")
