INSERT INTO items VALUES (3143, 'Randuin''s Omen');
INSERT INTO items VALUES (3147, 'Duskblade of Draktharr');
INSERT INTO items VALUES (3078, 'Trinity Force');
INSERT INTO items VALUES (3152, 'Hextech Protobelt-01');
INSERT INTO items VALUES (3630, 'Siege Teleport');
INSERT INTO items VALUES (3504, 'Ardent Censer');
INSERT INTO items VALUES (3461, 'Golden Transcendence (Disabled)');
INSERT INTO items VALUES (3341, 'Sweeping Lens (Trinket)');
INSERT INTO items VALUES (3222, 'Mikael''s Crucible');
INSERT INTO items VALUES (3462, 'Seer Stone (Trinket)');
INSERT INTO items VALUES (3096, 'Nomad''s Medallion');
INSERT INTO items VALUES (3153, 'Blade of the Ruined King');
INSERT INTO items VALUES (3641, 'Vanguard Banner');
INSERT INTO items VALUES (3117, 'Boots of Mobility');
INSERT INTO items VALUES (3800, 'Righteous Glory');
INSERT INTO items VALUES (1039, 'Hunter''s Talisman');
INSERT INTO items VALUES (3091, 'Wit''s End');
INSERT INTO items VALUES (3024, 'Glacial Shroud');
INSERT INTO items VALUES (2043, 'Vision Ward');
INSERT INTO items VALUES (3030, 'Hextech GLP-800');
INSERT INTO items VALUES (3145, 'Hextech Revolver');
INSERT INTO items VALUES (2302, 'Eye of the Oasis');
INSERT INTO items VALUES (3634, 'Tower: Beam of Ruination');
INSERT INTO items VALUES (2031, 'Refillable Potion');
INSERT INTO items VALUES (3090, 'Wooglet''s Witchcap');
INSERT INTO items VALUES (3157, 'Zhonya''s Hourglass');
INSERT INTO items VALUES (1413, 'Enchantment: Cinderhulk');
INSERT INTO items VALUES (3070, 'Tear of the Goddess');
INSERT INTO items VALUES (1004, 'Faerie Charm');
INSERT INTO items VALUES (3635, 'Port Pad');
INSERT INTO items VALUES (3044, 'Phage');
INSERT INTO items VALUES (1027, 'Sapphire Crystal');
INSERT INTO items VALUES (3647, 'Shield Totem');
INSERT INTO items VALUES (3009, 'Boots of Swiftness');
INSERT INTO items VALUES (3301, 'Ancient Coin');
INSERT INTO items VALUES (3053, 'Sterak''s Gage');
INSERT INTO items VALUES (3089, 'Rabadon''s Deathcap');
INSERT INTO items VALUES (3631, 'Siege Ballista');
INSERT INTO items VALUES (1018, 'Cloak of Agility');
INSERT INTO items VALUES (3003, 'Archangel''s Staff');
INSERT INTO items VALUES (3903, 'Raise Morale');
INSERT INTO items VALUES (3022, 'Frozen Mallet');
INSERT INTO items VALUES (3401, 'Face of the Mountain');
INSERT INTO items VALUES (2032, 'Hunter''s Potion');
INSERT INTO items VALUES (3097, 'Targon''s Brace');
INSERT INTO items VALUES (3165, 'Morellonomicon');
INSERT INTO items VALUES (3041, 'Mejai''s Soulstealer');
INSERT INTO items VALUES (3901, 'Fire at Will');
INSERT INTO items VALUES (3073, 'Tear of the Goddess (Quick Charge)');
INSERT INTO items VALUES (3060, 'Banner of Command');
INSERT INTO items VALUES (3048, 'Seraph''s Embrace');
INSERT INTO items VALUES (3020, 'Sorcerer''s Shoes');
INSERT INTO items VALUES (3135, 'Void Staff');
INSERT INTO items VALUES (3200, 'Prototype Hex Core');
INSERT INTO items VALUES (2049, 'Sightstone');
INSERT INTO items VALUES (3075, 'Thornmail');
INSERT INTO items VALUES (3181, 'Sanguine Blade');
INSERT INTO items VALUES (3303, 'Spellthief''s Edge');
INSERT INTO items VALUES (3067, 'Kindlegem');
INSERT INTO items VALUES (3028, 'Chalice of Harmony');
INSERT INTO items VALUES (1026, 'Blasting Wand');
INSERT INTO items VALUES (3085, 'Runaan''s Hurricane');
INSERT INTO items VALUES (3050, 'Zeke''s Harbinger');
INSERT INTO items VALUES (3004, 'Manamune');
INSERT INTO items VALUES (3190, 'Locket of the Iron Solari');
INSERT INTO items VALUES (3100, 'Lich Bane');
INSERT INTO items VALUES (3115, 'Nashor''s Tooth');
INSERT INTO items VALUES (2052, 'Poro-Snax');
INSERT INTO items VALUES (3363, 'Farsight Alteration');
INSERT INTO items VALUES (3348, 'Arcane Sweeper');
INSERT INTO items VALUES (1419, 'Enchantment: Bloodrazor');
INSERT INTO items VALUES (3134, 'Serrated Dirk');
INSERT INTO items VALUES (3640, 'Flash Zone');
INSERT INTO items VALUES (1052, 'Amplifying Tome');
INSERT INTO items VALUES (3706, 'Stalker''s Blade');
INSERT INTO items VALUES (1053, 'Vampiric Scepter');
INSERT INTO items VALUES (2301, 'Eye of the Watchers');
INSERT INTO items VALUES (3098, 'Frostfang');
INSERT INTO items VALUES (3362, 'Greater Vision Totem (Trinket)');
INSERT INTO items VALUES (1418, 'Enchantment: Bloodrazor');
INSERT INTO items VALUES (3285, 'Luden''s Echo');
INSERT INTO items VALUES (3124, 'Guinsoo''s Rageblade');
INSERT INTO items VALUES (3092, 'Frost Queen''s Claim');
INSERT INTO items VALUES (3069, 'Talisman of Ascension');
INSERT INTO items VALUES (3052, 'Jaurim''s Fist');
INSERT INTO items VALUES (3136, 'Haunting Guise');
INSERT INTO items VALUES (1402, 'Enchantment: Runic Echoes');
INSERT INTO items VALUES (3364, 'Oracle Alteration');
INSERT INTO items VALUES (3006, 'Berserker''s Greaves');
INSERT INTO items VALUES (3010, 'Catalyst of Aeons');
INSERT INTO items VALUES (3113, 'Aether Wisp');
INSERT INTO items VALUES (3174, 'Athene''s Unholy Grail');
INSERT INTO items VALUES (2033, 'Corrupting Potion');
INSERT INTO items VALUES (1036, 'Long Sword');
INSERT INTO items VALUES (3033, 'Mortal Reminder');
INSERT INTO items VALUES (1038, 'B. F. Sword');
INSERT INTO items VALUES (3123, 'Executioner''s Calling');
INSERT INTO items VALUES (3077, 'Tiamat');
INSERT INTO items VALUES (3197, 'The Hex Core mk-2');
INSERT INTO items VALUES (3801, 'Crystalline Bracer');
INSERT INTO items VALUES (1057, 'Negatron Cloak');
INSERT INTO items VALUES (3025, 'Iceborn Gauntlet');
INSERT INTO items VALUES (3031, 'Infinity Edge');
INSERT INTO items VALUES (3040, 'Seraph''s Embrace');
INSERT INTO items VALUES (2303, 'Eye of the Equinox');
INSERT INTO items VALUES (2015, 'Kircheis Shard');
INSERT INTO items VALUES (1401, 'Enchantment: Cinderhulk');
INSERT INTO items VALUES (1055, 'Doran''s Blade');
INSERT INTO items VALUES (3902, 'Death''s Daughter');
INSERT INTO items VALUES (3184, 'Guardian''s Hammer');
INSERT INTO items VALUES (3068, 'Sunfire Cape');
INSERT INTO items VALUES (3001, 'Abyssal Scepter');
INSERT INTO items VALUES (1054, 'Doran''s Shield');
INSERT INTO items VALUES (3139, 'Mercurial Scimitar');
INSERT INTO items VALUES (3198, 'Perfect Hex Core');
INSERT INTO items VALUES (3104, 'Lord Van Damm''s Pillager');
INSERT INTO items VALUES (3671, 'Enchantment: Warrior');
INSERT INTO items VALUES (3648, 'Siege Teleport (Inactive)');
INSERT INTO items VALUES (3111, 'Mercury''s Treads');
INSERT INTO items VALUES (3102, 'Banshee''s Veil');
INSERT INTO items VALUES (3087, 'Statikk Shiv');
INSERT INTO items VALUES (1028, 'Ruby Crystal');
INSERT INTO items VALUES (3133, 'Caulfield''s Warhammer');
INSERT INTO items VALUES (1083, 'Cull');
INSERT INTO items VALUES (1400, 'Enchantment: Warrior');
INSERT INTO items VALUES (2010, 'Total Biscuit of Rejuvenation');
INSERT INTO items VALUES (3086, 'Zeal');
INSERT INTO items VALUES (2050, 'Explorer''s Ward');
INSERT INTO items VALUES (3643, 'Entropy Field');
INSERT INTO items VALUES (3715, 'Skirmisher''s Sabre');
INSERT INTO items VALUES (3211, 'Spectre''s Cowl');
INSERT INTO items VALUES (2053, 'Raptor Cloak');
INSERT INTO items VALUES (2051, 'Guardian''s Horn');
INSERT INTO items VALUES (3508, 'Essence Reaver');
INSERT INTO items VALUES (3748, 'Titanic Hydra');
INSERT INTO items VALUES (3636, 'Tower: Storm Bulwark');
INSERT INTO items VALUES (3156, 'Maw of Malmortius');
INSERT INTO items VALUES (3112, 'Guardian''s Orb');
INSERT INTO items VALUES (3094, 'Rapid Firecannon');
INSERT INTO items VALUES (3065, 'Spirit Visage');
INSERT INTO items VALUES (1410, 'Enchantment: Runic Echoes');
INSERT INTO items VALUES (2003, 'Health Potion');
INSERT INTO items VALUES (3751, 'Bami''s Cinder');
INSERT INTO items VALUES (3642, 'Siege Refund');
INSERT INTO items VALUES (3361, 'Greater Stealth Totem (Trinket)');
INSERT INTO items VALUES (3187, 'Arcane Sweeper');
INSERT INTO items VALUES (1412, 'Enchantment: Warrior');
INSERT INTO items VALUES (1029, 'Cloth Armor');
INSERT INTO items VALUES (3034, 'Giant Slayer');
INSERT INTO items VALUES (3083, 'Warmog''s Armor');
INSERT INTO items VALUES (3071, 'The Black Cleaver');
INSERT INTO items VALUES (3029, 'Rod of Ages (Quick Charge)');
INSERT INTO items VALUES (3072, 'The Bloodthirster');
INSERT INTO items VALUES (1051, 'Brawler''s Gloves');
INSERT INTO items VALUES (2140, 'Elixir of Wrath');
INSERT INTO items VALUES (1033, 'Null-Magic Mantle');
INSERT INTO items VALUES (2054, 'Diet Poro-Snax');
INSERT INTO items VALUES (3633, 'Siege Teleport');
INSERT INTO items VALUES (2009, 'Total Biscuit of Rejuvenation');
INSERT INTO items VALUES (3191, 'Seeker''s Armguard');
INSERT INTO items VALUES (3122, 'Wicked Hatchet');
INSERT INTO items VALUES (3047, 'Ninja Tabi');
INSERT INTO items VALUES (3116, 'Rylai''s Crystal Scepter');
INSERT INTO items VALUES (3512, 'Zz''Rot Portal');
INSERT INTO items VALUES (3812, 'Death''s Dance');
INSERT INTO items VALUES (1037, 'Pickaxe');
INSERT INTO items VALUES (1408, 'Enchantment: Warrior');
INSERT INTO items VALUES (3170, 'Moonflair Spellblade');
INSERT INTO items VALUES (3460, 'Golden Transcendence');
INSERT INTO items VALUES (3711, 'Tracker''s Knife');
INSERT INTO items VALUES (3008, 'Manamune (Quick Charge)');
INSERT INTO items VALUES (2138, 'Elixir of Iron');
INSERT INTO items VALUES (3007, 'Archangel''s Staff (Quick Charge)');
INSERT INTO items VALUES (3140, 'Quicksilver Sash');
INSERT INTO items VALUES (3082, 'Warden''s Mail');
INSERT INTO items VALUES (3105, 'Aegis of the Legion');
INSERT INTO items VALUES (3649, 'Siege Sight Warder');
INSERT INTO items VALUES (3599, 'The Black Spear');
INSERT INTO items VALUES (3302, 'Relic Shield');
INSERT INTO items VALUES (1058, 'Needlessly Large Rod');
INSERT INTO items VALUES (2045, 'Ruby Sightstone');
INSERT INTO items VALUES (3035, 'Last Whisper');
INSERT INTO items VALUES (3146, 'Hextech Gunblade');
INSERT INTO items VALUES (3742, 'Dead Man''s Plate');
INSERT INTO items VALUES (3042, 'Muramana');
INSERT INTO items VALUES (3084, 'Overlord''s Bloodmail');
INSERT INTO items VALUES (3110, 'Frozen Heart');
INSERT INTO items VALUES (1416, 'Enchantment: Bloodrazor');
INSERT INTO items VALUES (3345, 'Soul Anchor (Trinket)');
INSERT INTO items VALUES (3056, 'Ohmwrecker');
INSERT INTO items VALUES (3645, 'Seer Stone (Trinket)');
INSERT INTO items VALUES (3144, 'Bilgewater Cutlass');
INSERT INTO items VALUES (3142, 'Youmuu''s Ghostblade');
INSERT INTO items VALUES (3137, 'Dervish Blade');
INSERT INTO items VALUES (3151, 'Liandry''s Torment');
INSERT INTO items VALUES (3057, 'Sheen');
INSERT INTO items VALUES (1409, 'Enchantment: Cinderhulk');
INSERT INTO items VALUES (3026, 'Guardian Angel');
INSERT INTO items VALUES (1041, 'Hunter''s Machete');
INSERT INTO items VALUES (3108, 'Fiendish Codex');
INSERT INTO items VALUES (3114, 'Forbidden Idol');
INSERT INTO items VALUES (2047, 'Oracle''s Extract');
INSERT INTO items VALUES (1006, 'Rejuvenation Bead');
INSERT INTO items VALUES (3101, 'Stinger');
INSERT INTO items VALUES (3074, 'Ravenous Hydra');
INSERT INTO items VALUES (3155, 'Hexdrinker');
INSERT INTO items VALUES (3027, 'Rod of Ages');
INSERT INTO items VALUES (3046, 'Phantom Dancer');
INSERT INTO items VALUES (3675, 'Enchantment: Bloodrazor');
INSERT INTO items VALUES (1011, 'Giant''s Belt');
INSERT INTO items VALUES (3158, 'Ionian Boots of Lucidity');
INSERT INTO items VALUES (3036, 'Lord Dominik''s Regards');
INSERT INTO items VALUES (1082, 'The Dark Seal');
INSERT INTO items VALUES (3673, 'Enchantment: Runic Echoes');
INSERT INTO items VALUES (1001, 'Boots of Speed');
INSERT INTO items VALUES (3340, 'Warding Totem (Trinket)');
INSERT INTO items VALUES (3043, 'Muramana');
INSERT INTO items VALUES (2139, 'Elixir of Sorcery');
INSERT INTO items VALUES (3672, 'Enchantment: Cinderhulk');
INSERT INTO items VALUES (1043, 'Recurve Bow');
INSERT INTO items VALUES (1042, 'Dagger');
INSERT INTO items VALUES (1414, 'Enchantment: Runic Echoes');
INSERT INTO items VALUES (1056, 'Doran''s Ring');
INSERT INTO items VALUES (3637, 'Nexus Siege: Siege Weapon Slot');
INSERT INTO items VALUES (3802, 'Lost Chapter');
INSERT INTO items VALUES (3196, 'The Hex Core mk-1');
INSERT INTO items VALUES (3185, 'The Lightbringer');
INSERT INTO items VALUES (1031, 'Chain Vest');
